version: '3.8'
services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    # container_name: proxy
    restart: unless-stopped
    environment:
      - ADMIN_DEFAULT_EMAIL=raphaelcarlosr@gmail.com
      - ADMIN_DEFAULT_PASSWORD=MySecurePassword
      - UID=1000
      - GID=1000
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - proxy-data:/data
      - proxy-certs:/etc/letsencrypt
    network_mode: "service:proxy"
    networks:
      - rapd-cloud

volumes:
  proxy-data:
  proxy-certs:
networks:
  rapd-cloud:
    external: true
