services:
  ywt-ydk-python:
    container_name: ywt-ydk-python
    image: mcr.microsoft.com/devcontainers/python:dev-3.9-bullseye
    command: sleep infinity
    networks:
      - ywteam
      - ywteam-dev
      - ywteam-ydk
    environment:
      - HOST_USER_ID=${UID:-1000}
      - HOST_GROUP_ID=${GID:-1000}
    volumes:
      - ..:/workspace:cached