version: '3.8'
services:
  wazuh-initializer:
    image: wazuh/wazuh-certs-generator:0.0.1
    hostname: wazuh.initializer
    volumes:
      - wazuh_certs:/certificates/
    networks:
      - wazuh
    entrypoint:
      - sh
      - -euc
      - |
        #!/bin/sh
        set -e
        mkdir -p /certificates
        mkdir -p /config
        hostname
        cat <<EOF > /config/certs.yml
        nodes:
          # Wazuh indexer server nodes
          indexer:
            - name: wazuh1.indexer
              ip: wazuh1.indexer
            - name: wazuh2.indexer
              ip: wazuh2.indexer
            - name: wazuh3.indexer
              ip: wazuh3.indexer

          # Wazuh server nodes
          # Use node_type only with more than one Wazuh manager
          server:
            - name: wazuh.master
              ip: wazuh.master
              node_type: master
            - name: wazuh.worker
              ip: wazuh.worker
              node_type: worker

          # Wazuh dashboard node
          dashboard:
            - name: wazuh-dashboard
              ip: wazuh.dashboard
        EOF
        if [ -z "$$(ls -A "/certificates")" ]; then
          echo "Creating certificates"
          /entrypoint.sh
        fi
        ls -lsa /certificates
    environment:
      - HTTP_PROXY=${WAZUH_HTTP_PROXY?WAZUH_HTTP_PROXY not set}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: none
        delay: 5s
        max_attempts: 3
        window: 120s
  wazuh-master:
    image: wazuh/wazuh-manager:4.5.2
    hostname: wazuh.master
    depends_on:
      - wazuh-initializer
    networks:
      - wazuh
    environment:
      - INDEXER_URL=${WAZUH_INDEXER_URL?WAZUH_INDEXER_URL not set}
      - INDEXER_USERNAME=${WAZUH_INDEXER_USERNAME?WAZUH_INDEXER_USERNAME not set}
      - INDEXER_PASSWORD=${WAZUH_INDEXER_PASSWORD?WAZUH_INDEXER_PASSWORD not set}
      - FILEBEAT_SSL_VERIFICATION_MODE=${WAZUH_FILEBEAT_SSL_VERIFICATION_MODE?WAZUH_FILEBEAT_SSL_VERIFICATION_MODE not set}
      - API_USERNAME=${WAZUH_API_USERNAME?WAZUH_API_USERNAME not set}
      - API_PASSWORD=${WAZUH_API_PASSWORD?WAZUH_API_PASSWORD not set}
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
    volumes:
      - ${WAZUH_CERTS_VOLUME_PATH?WAZUH_CERTS_VOLUME_PATH not set}/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ${WAZUH_CERTS_VOLUME_PATH?WAZUH_CERTS_VOLUME_PATH not set}/wazuh.master.pem:/etc/ssl/filebeat.pem
      - ${WAZUH_CERTS_VOLUME_PATH?WAZUH_CERTS_VOLUME_PATH not set}/wazuh.master-key.pem:/etc/ssl/filebeat.key
      - wazuh_master_api_configuration:/var/ossec/api/configuration
      - wazuh_master_etc:/var/ossec/etc
      - wazuh_master_logs:/var/ossec/logs
      - wazuh_master_queue:/var/ossec/queue
      - wazuh_master_va_multigroups:/var/ossec/var/multigroups
      - wazuh_master_integrations:/var/ossec/integrations
      - wazuh_master_active_response:/var/ossec/active-response/bin
      - wazuh_master_agentless:/var/ossec/agentless
      - wazuh_master_wodles:/var/ossec/wodles
      - wazuh_master_filebeat-etc:/etc/filebeat
      - wazuh_master_filebeat-var:/var/lib/filebeat      
      - ${SERVICE_VOLUME_PATH?SERVICE_VOLUME_PATH not set}/config/manager.conf:/wazuh-config-mount/etc/ossec.conf
    ports:
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: none
        delay: 5s
        max_attempts: 3
        window: 120s
  wazuh-worker:
    image: wazuh/wazuh-manager:4.5.2
    hostname: wazuh.worker
    environment:
      - INDEXER_URL=${WAZUH_INDEXER_URL?WAZUH_INDEXER_URL not set}
      - INDEXER_USERNAME=${WAZUH_INDEXER_USERNAME?WAZUH_INDEXER_USERNAME not set}
      - INDEXER_PASSWORD=${WAZUH_INDEXER_PASSWORD?WAZUH_INDEXER_PASSWORD not set}
      - FILEBEAT_SSL_VERIFICATION_MODE=${WAZUH_FILEBEAT_SSL_VERIFICATION_MODE?WAZUH_FILEBEAT_SSL_VERIFICATION_MODE not set}
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_KEY=/etc/ssl/filebeat.key
    networks:
      - wazuh
    volumes:
      - ${WAZUH_CERTS_VOLUME_PATH?WAZUH_CERTS_VOLUME_PATH not set}/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ${WAZUH_CERTS_VOLUME_PATH?WAZUH_CERTS_VOLUME_PATH not set}/wazuh.worker.pem:/etc/ssl/filebeat.pem
      - ${WAZUH_CERTS_VOLUME_PATH?WAZUH_CERTS_VOLUME_PATH not set}/wazuh.worker-key.pem:/etc/ssl/filebeat.key
      - wazuh_master_api_configuration:/var/ossec/api/configuration
      - wazuh_master_etc:/var/ossec/etc
      - wazuh_master_logs:/var/ossec/logs
      - wazuh_master_queue:/var/ossec/queue
      - wazuh_master_va_multigroups:/var/ossec/var/multigroups
      - wazuh_master_integrations:/var/ossec/integrations
      - wazuh_master_active_response:/var/ossec/active-response/bin
      - wazuh_master_agentless:/var/ossec/agentless
      - wazuh_master_wodles:/var/ossec/wodles
      - wazuh_master_filebeat-etc:/etc/filebeat
      - wazuh_master_filebeat-var:/var/lib/filebeat      
      - ${SERVICE_VOLUME_PATH?SERVICE_VOLUME_PATH not set}/config/worker.conf:/wazuh-config-mount/etc/ossec.conf
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: none
        delay: 5s
        max_attempts: 3
        window: 120s
  wazuh-indexer-1:
    image: wazuh/wazuh-indexer:4.5.2
    hostname: wazuh1.indexer
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - FILEBEAT_SSL_VERIFICATION_MODE=${WAZUH_FILEBEAT_SSL_VERIFICATION_MODE?WAZUH_FILEBEAT_SSL_VERIFICATION_MODE not set}
      # - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca-manager.pem
      # - SSL_CERTIFICATE=/etc/ssl/wazuh1.indexer.pem
      # - SSL_KEY=/etc/ssl/wazuh1.indexer-key.pem
    ports:
      - "9200:9200"
    networks:
      - wazuh
    volumes:
      - ${WAZUH_CERTS_VOLUME_PATH?WAZUH_CERTS_VOLUME_PATH not set}/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
      - ${WAZUH_CERTS_VOLUME_PATH?WAZUH_CERTS_VOLUME_PATH not set}/wazuh1.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh1.indexer.key
      - ${WAZUH_CERTS_VOLUME_PATH?WAZUH_CERTS_VOLUME_PATH not set}/wazuh1.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh1.indexer.pem
      - ${WAZUH_CERTS_VOLUME_PATH?WAZUH_CERTS_VOLUME_PATH not set}/admin.pem:/usr/share/wazuh-indexer/certs/admin.pem
      - ${WAZUH_CERTS_VOLUME_PATH?WAZUH_CERTS_VOLUME_PATH not set}/admin-key.pem:/usr/share/wazuh-indexer/certs/admin-key.pem
      - wazuh_indexer_1_data:/var/lib/wazuh-indexer
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: none
        delay: 5s
        max_attempts: 3
        window: 120s
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  wazuh-indexer-2:
    image: wazuh/wazuh-indexer:4.5.2
    hostname: wazuh2.indexer
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - FILEBEAT_SSL_VERIFICATION_MODE=${WAZUH_FILEBEAT_SSL_VERIFICATION_MODE?WAZUH_FILEBEAT_SSL_VERIFICATION_MODE not set}
      # - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca-manager.pem
      # - SSL_CERTIFICATE=/etc/ssl/wazuh2.indexer.pem
      # - SSL_KEY=/etc/ssl/wazuh2.indexer-key.pem
    ports:
      - "9201:9200"
    networks:
      - wazuh
    volumes:
      - ${WAZUH_CERTS_VOLUME_PATH?WAZUH_CERTS_VOLUME_PATH not set}/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
      - ${WAZUH_CERTS_VOLUME_PATH?WAZUH_CERTS_VOLUME_PATH not set}/wazuh2.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh2.indexer.key
      - ${WAZUH_CERTS_VOLUME_PATH?WAZUH_CERTS_VOLUME_PATH not set}/wazuh2.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh2.indexer.pem
      - wazuh_indexer_2_data:/var/lib/wazuh-indexer
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: none
        delay: 5s
        max_attempts: 3
  wazuh-indexer-3:
    image: wazuh/wazuh-indexer:4.5.2
    hostname: wazuh3.indexer
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - FILEBEAT_SSL_VERIFICATION_MODE=${WAZUH_FILEBEAT_SSL_VERIFICATION_MODE?WAZUH_FILEBEAT_SSL_VERIFICATION_MODE not set}      
    ports:
      - "9202:9200"
    networks:
      - wazuh
    volumes:
      - ${WAZUH_CERTS_VOLUME_PATH?WAZUH_CERTS_VOLUME_PATH not set}/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
      - ${WAZUH_CERTS_VOLUME_PATH?WAZUH_CERTS_VOLUME_PATH not set}/wazuh3.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh3.indexer.key
      - ${WAZUH_CERTS_VOLUME_PATH?WAZUH_CERTS_VOLUME_PATH not set}/wazuh3.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh3.indexer.pem
      - wazuh_indexer_3_data:/var/lib/wazuh-indexer
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: none
  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.5.2
    hostname: wazuh.dashboard
    depends_on:
      - wazuh-initializer
      - wazuh-indexer-1
    networks:
      - wazuh
    environment:
      - OPENSEARCH_HOSTS=ttps://wazuh1.indexer:9200
      - WAZUH_API_URL="https://wazuh.master"
      - API_USERNAME=${WAZUH_API_USERNAME?WAZUH_API_USERNAME not set}
      - API_PASSWORD=${WAZUH_API_PASSWORD?WAZUH_API_PASSWORD not set}
      - DASHBOARD_USERNAME=${WAZUH_DASHBOARD_USERNAME?WAZUH_DASHBOARD_USERNAME not set}
      - DASHBOARD_PASSWORD=${WAZUH_DASHBOARD_PASSWORD?WAZUH_DASHBOARD_PASSWORD not set}
    volumes:
      - ${WAZUH_CERTS_VOLUME_PATH?WAZUH_CERTS_VOLUME_PATH not set}/wazuh.dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - ${WAZUH_CERTS_VOLUME_PATH?WAZUH_CERTS_VOLUME_PATH not set}/wazuh.dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - ${WAZUH_CERTS_VOLUME_PATH?WAZUH_CERTS_VOLUME_PATH not set}/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem
    ports:
      - "443:5601"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: none
        delay: 5s
        max_attempts: 3
        window: 120s
  wazuh-nginx:
    image: nginx:stable
    hostname: wazuh.nginx
    restart: always
    ports:
      - "1514:1514"
    depends_on:
      - wazuh.master
      - wazuh.worker
      - wazuh.dashboard
    links:
      - wazuh.master:wazuh.master
      - wazuh.worker:wazuh.worker
      - wazuh.dashboard:wazuh.dashboard
    # volumes:
    #   - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  # wazuh-agent:
  #   image: wazuh/wazuh-agent:4.5.2
  #   networks:
  #     - wazuh
  #   environment:
  #     - WAZUH_MANAGER=${WAZUH_MANAGER?WAZUH_MANAGER not set}
  #     - WAZUH_AGENT_NAME=${WAZUH_AGENT_NAME?WAZUH_AGENT_NAME not set}
  #     - WAZUH_AGENT_GROUP=${WAZUH_AGENT_GROUP?WAZUH_AGENT_GROUP not set}
  #     - WAZUH_AGENT_PASSWORD=${WAZUH_AGENT_PASSWORD?WAZUH_AGENT_PASSWORD not set}
  #     - WAZUH_AGENT_CA=${WAZUH_AGENT_CA?WAZUH_AGENT_CA not set}
  #     - WAZUH_AGENT_CERT=${WAZUH_AGENT_CERT?WAZUH_AGENT_CERT not set}
  #     - WAZUH_AGENT_KEY=${WAZUH_AGENT_KEY?WAZUH_AGENT_KEY not set}
  #     - WAZUH_AGENT_CONFIG=${WAZUH_AGENT_CONFIG?WAZUH_AGENT_CONFIG not set}
  #     - WAZUH_AGENT_ENABLE_FILEBEAT=${WAZUH_AGENT_ENABLE_FILEBEAT?WAZUH_AGENT_ENABLE_FILEBEAT not set}
  #     - WAZUH_AGENT_ENABLE_ROOTCHECK=${WAZUH_AGENT_ENABLE_ROOTCHECK?WAZUH_AGENT_ENABLE_ROOTCHECK not set}
  #     - WAZUH_AGENT_ENABLE_SYSCHECK=${WAZUH_AGENT_ENABLE_SYSCHECK?WAZUH_AGENT_ENABLE_SYSCHECK not set}
  #     - WAZUH_AGENT_ENABLE_OSQUERY=${WAZUH_AGENT_ENABLE_OSQUERY?WAZUH_AGENT_ENABLE_OSQUERY not set}
  #     - WAZUH_AGENT_ENABLE_DOCKER=${WAZUH_AGENT_ENABLE_DOCKER?WAZUH_AGENT_ENABLE_DOCKER not set}
  #     - WAZUH_AGENT_ENABLE_KUBERNETES=${WAZUH_AGENT_ENABLE_KUBERNETES?WAZUH_AGENT_ENABLE_KUBERNETES not set}
  #     - WAZUH_AGENT_ENABLE_AWS=${WAZUH_AGENT_ENABLE_AWS?WAZUH_AGENT_ENABLE_AWS not set}
  #     - WAZUH_AGENT_ENABLE_CLOUDTRAIL=${WAZUH_AGENT_ENABLE_CLOUDTRAIL?WAZUH_AGENT_ENABLE_CLOUDTRAIL not set}

  

volumes:
  wazuh_certs:
  wazuh_master_api_configuration:
  wazuh_master_etc:
  wazuh_master_logs:
  wazuh_master_queue:
  wazuh_master_va_multigroups:
  wazuh_master_integrations:
  wazuh_master_active_response:
  wazuh_master_agentless:
  wazuh_master_wodles:
  wazuh_master_filebeat-etc:
  wazuh_master_filebeat-var:  
  wazuh_indexer_1_data:
  wazuh_indexer_2_data:
  wazuh_indexer_3_data:

networks:
  wazuh:
    name: ${TENANT_NAME?Tenanat network name not set}_wazuh
  tenant:
    name: ${TENANT_NAME?Tenanat network name not set}_tenant
    external: true
  edge:
    name: ${EDGE_NETWORK_NAME?EDGE_NETWORK_NAME not set}
    external: true