name: ywteam-ydk
services:
  ywt-ydk-shell:
    container_name: ywt-ydk-shell
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - ydk
    build: 
      context: .
      dockerfile: ./Dockerfile
      args:
        - USER_ID=${UID:-1000}
        - GROUP_ID=${GID:-1000}
    environment:
      - NODE_ENV=development
      - HOST_USER_ID=${UID:-1000}
      - HOST_GROUP_ID=${GID:-1000}
    volumes:
      - ../../../..:/workspace:cached
      # - ../../src/shell:/workspace/src:cached
      # - ../../../../.git:/workspace/.git:cached
      # - ../../../../.gitignore:/workspace/.gitignore:cached
      # - ../../../../.gitmodules:/workspace/.gitmodules:cached